{% set name = "opentelemetry-exporter-opencensus" %}
{% set version = "0.30b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-opencensus-{{ version }}.tar.gz
  sha256: 440834b5314a2bae99485864ae19ee62041c02602d51990ac71374c1a54f3ad0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - grpcio <2.0.0,>=1.0.0
    - opencensus-proto <1.0.0,>=0.1.0
    - opentelemetry-api ~=1.3
    - opentelemetry-sdk ~=1.3
    - protobuf >=3.13.0
    - python >=3.6
    # - setuptools >=16.0
    # - setuptools >=16.0
    # - setuptools >=16.0
    # - setuptools >=16.0
    # - setuptools >=16.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-opencensus
  summary: OpenCensus Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
