{% set name = "opentelemetry-exporter-opencensus" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_opencensus-{{ version }}.tar.gz
  sha256: 48e109a959ec1c7ebd875d546b990e288596991a9b7bd4461858103b6fd4164a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - grpcio <2.0.0,>=1.0.0
    - opencensus-proto <1.0.0,>=0.1.0
    - opentelemetry-api >=1.21.0
    - opentelemetry-sdk >=1.15
    - protobuf ~=3.13
    - setuptools >=16.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-opencensus
  summary: OpenCensus Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
